### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by houd1ni** [houd1ni/Marmott2#1]
- [ ]  Samples / Server-Side tests rewrite to Node.js
- [ ]  Cache handling
- [ ]  Improve docs, make them on different pages, with useful structure
- [ ]  Multifile upload
- [ ]  Data + files boundle
- [ ]  Run some callback just before
- [ ]  Run some callback while a part is loaded
- [ ]  Run some callback if some timeout expired
- [ ]  Code review, refactor, improve  minify-ready
- [ ]  Adapters for different input data. E.g. jQuery's formats of $.ajax and, maybe aliases-shortcuts
- [ ]  Different builds for different purposes
- [ ]  WebSockets adaptation
- [ ] Show it to the World
